version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 10
    reviewers:
      - "lluminata-team"
    assignees:
      - "lluminata-team"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      nextjs:
        patterns:
          - "next*"
          - "@next/*"
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "playwright*"
        update-types:
          - "minor"
          - "patch"
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
